from __future__ import annotations

from typing import Any

from .._shared import (
    as_mapping,
    ensure_text,
    extract_scalar_token,
    flatten_token_map,
    name_has_prefix,
    read_template_text,
    slugify,
    style_map_to_css,
)


COMPONENT_STYLESHEET_PARTS: tuple[tuple[str, ...], ...] = (
    ("hugo", "assets", "css", "components", "link-grid.css"),
    ("hugo", "assets", "css", "components", "accordion.css"),
    ("hugo", "assets", "css", "components", "carousel.css"),
    ("hugo", "assets", "css", "components", "form.css"),
    ("hugo", "assets", "css", "components", "section-block.css"),
)


class CssGenerator:
    """Génère la feuille de style calculée à partir du modèle canonique.

    Le rôle de ce générateur est volontairement limité :
    - poser le "shell" CSS minimal commun à toutes les sorties ;
    - injecter, si demandé, les presets de composants partagés ;
    - écrire la géométrie absolue et les styles issus de Figma.
    """

    def __init__(self, *, include_component_presets: bool = True) -> None:
        # En sortie Hugo, les presets de composants vivent dans un fichier partagé
        # dédié. En sortie statique, on les réinjecte dans `styles.css`.
        self._include_component_presets = include_component_presets

    def generate(self, page_data: dict[str, Any]) -> str:
        page = page_data.get("page", {})
        sections = page_data.get("sections", [])
        tokens = page_data.get("tokens", {})
        page_width, page_height, page_origin_x, page_origin_y = self._page_geometry(page, sections)
        lines = [
            *self._font_imports(page_data),
            "/* Generated by figma2hugo. */",
            "",
            *self._root_variable_lines(page_width, tokens),
            *self._base_shell_lines(page_width, page_height),
        ]
        if self._include_component_presets:
            lines.extend(self._component_preset_lines())
        flow_cursor_bottom = 0.0
        for section in sections:
            section_lines, flow_cursor_bottom = self._section_rules(
                section,
                page_width,
                page_origin_x,
                page_origin_y,
                flow_cursor_bottom=flow_cursor_bottom,
            )
            lines.extend(section_lines)
        lines.extend(self._responsive_override_lines(page_data))
        return "\n".join(lines) + "\n"

    def _root_variable_lines(self, page_width: int, tokens: dict[str, Any]) -> list[str]:
        lines = [
            ":root {",
            f"  --page-max-width: {page_width}px;",
            "  --page-shell-gutter: clamp(16px, 3vw, 32px);",
            "  --surface-page: #ffffff;",
            "  --text-color: #171717;",
        ]
        lines.extend(self._token_variables("color", tokens.get("colors", {})))
        lines.extend(self._token_variables("space", tokens.get("spacing", {})))
        lines.extend(self._token_variables("font", tokens.get("typography", {})))
        lines.extend(self._token_variables("shadow", tokens.get("shadows", {})))
        lines.extend(self._token_variables("radius", tokens.get("radii", {})))
        lines.append("}")
        return lines

    def _base_shell_lines(self, page_width: int, page_height: int) -> list[str]:
        return [
            "",
            "*,",
            "*::before,",
            "*::after {",
            "  box-sizing: border-box;",
            "}",
            "",
            "html {",
            "  font-size: 16px;",
            "  scroll-behavior: smooth;",
            "}",
            "",
            "body {",
            "  margin: 0;",
            "  min-width: 0;",
            "  min-height: 100vh;",
            '  font-family: var(--font-body-family, "Segoe UI", sans-serif);',
            "  color: var(--text-color);",
            "  background: var(--surface-page);",
            "  overflow-x: auto;",
            "}",
            "",
            "img {",
            "  display: block;",
            "}",
            "",
            "a {",
            "  color: inherit;",
            "  text-decoration: none;",
            "}",
            "",
            ".page {",
            "  position: relative;",
            "  width: var(--page-max-width);",
            "  max-width: none;",
            f"  min-height: {page_height}px;" if page_height else "  min-height: 100vh;",
            "  margin: 0 auto;",
            "}",
            "",
            '.page[data-page-shell="flow"] {',
            "  width: min(100%, var(--page-max-width));",
            "  max-width: var(--page-max-width);",
            "  min-height: 100vh;",
            "}",
            "",
            ".page-main {",
            "  position: relative;",
            "  display: block;",
            "}",
            "",
            ".page-section {",
            "  position: relative;",
            "  left: auto;",
            "  top: auto;",
            "  width: 100%;",
            "  padding: 0;",
            "  overflow: visible;",
            "}",
            "",
            ".page-section__inner {",
            "  position: relative;",
            "  width: 100%;",
            "  overflow: visible;",
            "}",
            "",
            '.page[data-page-shell="flow"] .page-section {',
            "  position: relative;",
            "  left: auto;",
            "  top: auto;",
            "  width: 100%;",
            "}",
            "",
            '.page[data-page-shell="flow"] .page-section__inner {',
            "  width: 100%;",
            "  height: auto;",
            "  min-height: 0;",
            "}",
            "",
            ".content-node,",
            ".content-text,",
            ".content-asset {",
            "  position: absolute;",
            "  margin: 0;",
            "}",
            "",
            "button.content-node {",
            "  -webkit-appearance: none;",
            "  appearance: none;",
            "  display: block;",
            "  padding: 0;",
            "  border: 0;",
            "  background: transparent;",
            "  color: inherit;",
            "  font: inherit;",
            "  line-height: inherit;",
            "  text-align: inherit;",
            "  cursor: inherit;",
            "}",
            "",
            ".content-text {",
            "  max-width: none;",
            "  transform-origin: top left;",
            "}",
            "",
            ".content-text span {",
            "  white-space: inherit;",
            "}",
            "",
            ".content-asset {",
            "  line-height: 0;",
            "}",
            "",
            ".content-asset img {",
            "  width: 100%;",
            "  height: 100%;",
            "  object-fit: contain;",
            "}",
            "",
            ".is-decorative {",
            "  pointer-events: none;",
            "  user-select: none;",
            "}",
        ]

    def _component_preset_lines(self) -> list[str]:
        # On concatène ici les styles de chaque composant pour la sortie
        # statique, alors qu'en sortie Hugo chaque famille garde son propre
        # fichier sous `assets/css/components/`.
        lines: list[str] = []
        for relative_parts in COMPONENT_STYLESHEET_PARTS:
            content = read_template_text(*relative_parts).strip()
            if not content:
                continue
            lines.extend(["", *content.splitlines()])
        return lines

    def _font_imports(self, page_data: dict[str, Any]) -> list[str]:
        fonts = self._collect_font_families(page_data)
        google_font_params = {
            "Inter": "family=Inter:ital,wght@0,100..900;1,100..900",
            "Roboto": "family=Roboto:ital,wght@0,100..900;1,100..900",
            "Roboto Slab": "family=Roboto+Slab:wght@100..900",
        }
        lines: list[str] = []
        selected = [google_font_params[font] for font in sorted(fonts) if font in google_font_params]
        if selected:
            lines.append(f'@import url("https://fonts.googleapis.com/css2?{"&".join(selected)}&display=swap");')
            lines.append("")
        return lines

    def _page_geometry(self, page: dict[str, Any], sections: list[dict[str, Any]]) -> tuple[int, int, float, float]:
        raw_width = int(float(page.get("width", 0) or 0))
        raw_height = int(float(page.get("height", 0) or 0))
        if not sections:
            return (raw_width or 1440, raw_height, 0.0, 0.0)

        section_bounds = [section.get("bounds", {}) or {} for section in sections]
        lefts = [float(bounds.get("x", 0) or 0) for bounds in section_bounds]
        tops = [float(bounds.get("y", 0) or 0) for bounds in section_bounds]
        rights = [
            float(bounds.get("x", 0) or 0) + float(bounds.get("width", 0) or 0)
            for bounds in section_bounds
        ]
        bottoms = [
            float(bounds.get("y", 0) or 0) + float(bounds.get("height", 0) or 0)
            for bounds in section_bounds
        ]

        origin_x = min(lefts)
        origin_y = min(tops)
        extent_width = max(0.0, max(rights) - origin_x)
        extent_height = max(0.0, max(bottoms) - origin_y)
        page_width = max(raw_width or 0, int(round(extent_width)) or 0) or 1440
        page_height = max(raw_height or 0, int(round(extent_height)) or 0)
        return page_width, page_height, origin_x, origin_y

    def _collect_font_families(self, page_data: dict[str, Any]) -> set[str]:
        families: set[str] = set()
        for text in page_data.get("texts", {}).values():
            style = text.get("style", {})
            family = ensure_text(style.get("fontFamily")).strip()
            if family:
                families.add(family)
            for segment in text.get("segments", []):
                style_text = ensure_text(segment.get("style"))
                marker = 'font-family: "'
                if marker in style_text:
                    rest = style_text.split(marker, 1)[1]
                    families.add(rest.split('"', 1)[0])
                elif "font-family:" in style_text:
                    rest = style_text.split("font-family:", 1)[1].split(";", 1)[0]
                    families.add(rest.replace('"', "").replace(", sans-serif", "").strip())
        return {family for family in families if family}

    def _token_variables(self, prefix: str, token_map: Any) -> list[str]:
        lines: list[str] = []
        for token_name, token_value in flatten_token_map(prefix, token_map):
            if not token_name:
                continue
            scalar = extract_scalar_token(token_value)
            if not scalar and isinstance(token_value, dict):
                if prefix == "font":
                    token_slug = slugify(token_name, "token")
                    family = ensure_text(token_value.get("fontFamily"))
                    size = ensure_text(token_value.get("fontSize"))
                    weight = ensure_text(token_value.get("fontWeight"))
                    line_height = ensure_text(token_value.get("lineHeight"))
                    if family:
                        lines.append(f'  --{token_slug}-family: "{family}";')
                    if size:
                        lines.append(f"  --{token_slug}-size: {size if any(ch.isalpha() for ch in size) else f'{size}px'};")
                    if weight:
                        lines.append(f"  --{token_slug}-weight: {weight};")
                    if line_height:
                        lines.append(
                            f"  --{token_slug}-line-height: {line_height if any(ch.isalpha() for ch in line_height) else line_height};"
                        )
                continue
            if scalar:
                token_slug = slugify(token_name, "token")
                lines.append(f"  --{token_slug}: {scalar};")
        return lines

    def _section_rules(
        self,
        section: dict[str, Any],
        page_width: int,
        page_origin_x: float,
        page_origin_y: float,
        *,
        flow_cursor_bottom: float,
    ) -> tuple[list[str], float]:
        section_class = section.get("class_name", "")
        bounds = section.get("bounds", {})
        section_left = float(bounds.get("x", 0) or 0) - page_origin_x
        section_top = float(bounds.get("y", 0) or 0) - page_origin_y
        section_height = int(float(bounds.get("height", 0) or 0))
        section_width = int(float(bounds.get("width", 0) or 0))
        is_flow_section = self._section_uses_flow_shell(section)
        asset_stack_overrides = self._infer_asset_stack_overrides(section)
        lines = ["", f"/* Section: {section.get('name', section.get('id', 'section'))} */"]
        if is_flow_section:
            section_margin_top = max(section_top - flow_cursor_bottom, 0.0)
            lines.extend(
                [
                    f".{section_class} {{",
                    *self._hidden_lines(section),
                    "  position: relative;",
                    "  left: auto;",
                    "  top: auto;",
                    f"  width: min(100%, {section_width}px);" if section_width else "  width: 100%;",
                    f"  max-width: {section_width}px;" if section_width else f"  max-width: {page_width}px;",
                    f"  margin-top: {section_margin_top:.2f}px;",
                    "  margin-inline: auto;",
                    f"  min-height: {section_height}px;" if section_height else "  min-height: 0;",
                    "}",
                    "",
                    f".{section_class} .page-section__inner {{",
                    "  width: 100%;",
                    f"  min-height: {section_height}px;" if section_height else "  min-height: 0;",
                    "  height: auto;",
                    "}",
                ]
            )
            next_flow_cursor_bottom = max(flow_cursor_bottom + section_margin_top + section_height, section_top + section_height)
        else:
            lines.extend(
                [
                    f".{section_class} {{",
                    *self._hidden_lines(section),
                    "  position: absolute;",
                    f"  left: {section_left:.2f}px;",
                    f"  top: {section_top:.2f}px;",
                    f"  width: {section_width}px;" if section_width else f"  width: {page_width}px;",
                    f"  height: {section_height}px;" if section_height else "  height: auto;",
                    f"  min-height: {section_height}px;" if section_height else "  min-height: 0;",
                    "}",
                    "",
                    f".{section_class} .page-section__inner {{",
                    f"  height: {section_height}px;" if section_height else "  height: auto;",
                    f"  width: {section_width}px;" if section_width else f"  width: {page_width}px;",
                    "}",
                ]
            )
            next_flow_cursor_bottom = flow_cursor_bottom
        section_inner_overflow = self._section_inner_overflow(section)
        if section_inner_overflow:
            lines.insert(-1, f"  overflow: {section_inner_overflow};")
        for index, node in enumerate(section.get("children", [])):
            lines.extend(self._node_rules(node, order=index, asset_stack_overrides=asset_stack_overrides))
        return lines, next_flow_cursor_bottom

    def _section_uses_flow_shell(self, section: dict[str, Any]) -> bool:
        layout = section.get("layout", {}) or {}
        if not bool(layout.get("use_flow_shell")):
            return False
        if not bool(layout.get("inferred_flow")):
            return False
        return ensure_text(layout.get("inferred_strategy")).strip().lower() == "flow"

    def _node_rules(self, node: dict[str, Any], *, order: int, asset_stack_overrides: dict[str, str]) -> list[str]:
        kind = node.get("kind")
        if kind == "text":
            text = dict(as_mapping(node.get("text")))
            if "responsive_default_hidden" not in text:
                text["responsive_default_hidden"] = bool(node.get("responsive_default_hidden"))
            return self._text_rules(text, order=order)
        if kind == "asset":
            asset = node.get("asset", {})
            asset_id = ensure_text(asset.get("id") or asset.get("node_id"))
            asset_data = dict(as_mapping(asset))
            if "responsive_default_hidden" not in asset_data:
                asset_data["responsive_default_hidden"] = bool(node.get("responsive_default_hidden"))
            return self._asset_rules(
                asset_data,
                order=order,
                stack_override=asset_stack_overrides.get(asset_id, ""),
            )
        class_name = ensure_text(node.get("class_name"))
        if not class_name:
            return []
        bounds = node.get("bounds", {})
        lines = [
            "",
            f".{class_name} {{",
            *self._hidden_lines(node),
            *self._absolute_box_rules(bounds),
            f"  z-index: {10 + order};",
            "}",
        ]
        for child_index, child in enumerate(node.get("children", [])):
            lines.extend(self._node_rules(child, order=child_index, asset_stack_overrides=asset_stack_overrides))
        return lines

    def _text_rules(self, text: dict[str, Any], *, order: int) -> list[str]:
        class_name = ensure_text(text.get("class_name"))
        if not class_name:
            return []
        tag_name = ensure_text(text.get("tag")).strip().lower()
        is_list = bool(text.get("list_items"))
        bounds = text.get("bounds", {})
        render_bounds = text.get("render_bounds", {}) or {}
        style_css = ensure_text(text.get("style_css"))
        nowrap = bool(text.get("nowrap"))
        preserve_spaces = bool(text.get("preserve_spaces"))
        centered_single_line_height = self._centered_single_line_box_height(text, bounds, render_bounds)
        white_space = "nowrap" if nowrap else "normal"
        if centered_single_line_height > 0:
            white_space = "nowrap"
        if preserve_spaces and nowrap:
            white_space = "pre"
        lines = [
            "",
            f".{class_name} {{",
            *self._hidden_lines(text),
            *self._absolute_box_rules(bounds, include_height=False),
            f"  white-space: {white_space};",
            f"  z-index: {400 + order};",
        ]
        if is_list:
            lines.extend(
                [
                    "  box-sizing: border-box;",
                    "  list-style-position: outside;",
                    f"  padding-inline-start: {'1.6em' if tag_name == 'ol' else '1.4em'};",
                ]
            )
        preferred_height = self._preferred_text_height(text, bounds, render_bounds)
        if preferred_height > 0 and self._should_preserve_text_height(text, tag_name):
            lines.append(f"  height: {preferred_height:.2f}px;")
            if tag_name not in {"h1", "h2", "h3", "h4", "h5", "h6", "label"}:
                lines.append("  overflow: hidden;")
        for declaration in self._effective_text_style_declarations(
            text,
            style_css,
            centered_single_line_height=centered_single_line_height,
        ):
            lines.append(f"  {declaration}")
        lines.append("}")
        if is_list:
            lines.extend(
                [
                    "",
                    f".{class_name} > li {{",
                    "  margin: 0;",
                    "}",
                ]
            )
        return lines

    def _should_preserve_text_height(self, text: dict[str, Any], tag_name: str) -> bool:
        if tag_name not in {"h1", "h2", "h3", "h4", "h5", "h6", "label"}:
            return True
        return self._text_is_multiline(text)

    def _text_is_multiline(self, text: dict[str, Any]) -> bool:
        display_line_count = int(text.get("display_line_count", 0) or 0)
        if display_line_count > 1:
            return True
        value = ensure_text(text.get("value") or text.get("plain_text"))
        normalized = value.replace("\r\n", "\n").replace("\r", "\n")
        return "\n" in normalized

    def _preferred_text_height(self, text: dict[str, Any], bounds: dict[str, Any], render_bounds: dict[str, Any]) -> float:
        bounds_height = float(bounds.get("height", 0) or 0)
        render_height = float(render_bounds.get("height", 0) or 0)
        if bounds_height > 0 and bool(text.get("normalized_break_lines")):
            source_line_count = int(text.get("source_line_count", 0) or 0)
            display_line_count = int(text.get("display_line_count", 0) or 0)
            line_height = self._numeric_line_height(text.get("style", {}))
            estimated_height = display_line_count * line_height
            if (
                source_line_count > display_line_count > 0
                and line_height > 0
                and 0 < estimated_height < bounds_height
            ):
                return estimated_height
        if bounds_height > 0:
            if (
                render_height > 0
                and render_height < bounds_height
                and self._has_spacer_breaks(text)
                and not self._has_compact_segment_line_height(text)
            ):
                return render_height
            return bounds_height
        return render_height

    def _centered_single_line_box_height(
        self,
        text: dict[str, Any],
        bounds: dict[str, Any],
        render_bounds: dict[str, Any],
    ) -> float:
        style = text.get("style", {}) or {}
        vertical_align = ensure_text(style.get("textAlignVertical")).strip().upper()
        if vertical_align != "CENTER":
            return 0.0
        value = ensure_text(text.get("value") or text.get("plain_text"))
        if not value or self._has_spacer_breaks(text):
            return 0.0
        if "\n" in value.replace("\r\n", "\n").replace("\r", "\n"):
            return 0.0
        bounds_height = float(bounds.get("height", 0) or 0)
        render_height = float(render_bounds.get("height", 0) or 0)
        font_size = float(style.get("fontSize", 0) or 0)
        line_height = self._numeric_line_height(style)
        if bounds_height <= 0 or font_size <= 0 or line_height <= 0:
            return 0.0
        if render_height <= 0:
            render_height = min(bounds_height, font_size)
        if render_height > max(font_size * 1.35, line_height * 1.6):
            return 0.0
        if bounds_height <= max(line_height * 1.35, render_height * 1.05):
            return 0.0
        return bounds_height

    def _has_spacer_breaks(self, text: dict[str, Any]) -> bool:
        value = ensure_text(text.get("value") or text.get("plain_text"))
        normalized = value.replace("\r\n", "\n").replace("\r", "\n")
        return "\n\n" in normalized or normalized.endswith("\n")

    def _has_compact_segment_line_height(self, text: dict[str, Any]) -> bool:
        return self._compact_segment_line_height(text) > 0

    def _compact_segment_line_height(self, text: dict[str, Any]) -> float:
        base_line_height = self._numeric_line_height(text.get("style", {}))
        if base_line_height <= 0:
            return 0.0
        candidate_line_heights: list[float] = []
        for segment in text.get("segments", []):
            segment_line_height = self._numeric_line_height(segment)
            if segment_line_height > 0 and segment_line_height < (base_line_height * 0.85):
                candidate_line_heights.append(segment_line_height)
        if not candidate_line_heights:
            return 0.0
        return min(candidate_line_heights)

    def _numeric_line_height(self, value: Any) -> float:
        if isinstance(value, dict):
            direct = value.get("lineHeight")
            if isinstance(direct, (int, float)):
                return float(direct)
            style_text = ensure_text(value.get("style"))
        else:
            style_text = ensure_text(value)
        if not style_text:
            return 0.0
        for declaration in self._split_css(style_text):
            if not declaration.startswith("line-height:"):
                continue
            raw_value = declaration.split(":", 1)[1].strip().rstrip(";").strip()
            if raw_value.endswith("px"):
                raw_value = raw_value[:-2].strip()
            try:
                return float(raw_value)
            except ValueError:
                return 0.0
        return 0.0

    def _effective_text_style_declarations(
        self,
        text: dict[str, Any],
        style_css: str,
        *,
        centered_single_line_height: float = 0.0,
    ) -> list[str]:
        declarations = self._split_css(style_css) if style_css else []
        if self._text_uses_segment_typography(text):
            declarations = self._strip_parent_typography_for_segmented_text(declarations)
        compact_line_height = self._compact_segment_line_height(text)
        if compact_line_height > 0:
            declarations = self._replace_line_height(declarations, compact_line_height)
        if centered_single_line_height > 0:
            declarations = self._replace_line_height(declarations, centered_single_line_height)
        if bool(text.get("preserve_spaces")) and bool(text.get("nowrap")):
            adjusted: list[str] = []
            for declaration in declarations:
                if declaration == "text-align: justify;":
                    adjusted.append("text-align: left;")
                else:
                    adjusted.append(declaration)
            declarations = adjusted
        return declarations

    def _text_uses_segment_typography(self, text: dict[str, Any]) -> bool:
        for segment in text.get("segments", []):
            style_text = ensure_text(segment.get("style")).strip()
            if not style_text:
                continue
            if any(
                marker in style_text
                for marker in (
                    "font-family:",
                    "font-size:",
                    "font-weight:",
                    "font-style:",
                    "line-height:",
                    "letter-spacing:",
                    "color:",
                )
            ):
                return True
        return False

    def _strip_parent_typography_for_segmented_text(self, declarations: list[str]) -> list[str]:
        blocked_prefixes = (
            "font-family:",
            "font-size:",
            "font-weight:",
            "font-style:",
            "line-height:",
            "letter-spacing:",
            "color:",
        )
        stripped: list[str] = []
        for declaration in declarations:
            if declaration.startswith(blocked_prefixes):
                continue
            stripped.append(declaration)
        return stripped

    def _replace_line_height(self, declarations: list[str], line_height: float) -> list[str]:
        updated: list[str] = []
        replaced = False
        for declaration in declarations:
            if declaration.startswith("line-height:"):
                updated.append(f"line-height: {line_height:.2f}px;")
                replaced = True
            else:
                updated.append(declaration)
        if not replaced:
            updated.append(f"line-height: {line_height:.2f}px;")
        return updated

    def _section_inner_overflow(self, section: dict[str, Any]) -> str:
        metadata = section.get("metadata", {}) or {}
        if bool(metadata.get("clipsContent")):
            return "hidden"
        if self._has_large_content_overflow(section):
            return "hidden"
        return ""

    def _has_large_content_overflow(self, section: dict[str, Any]) -> bool:
        section_bounds = section.get("bounds", {}) or {}
        section_width = float(section_bounds.get("width", 0) or 0)
        section_height = float(section_bounds.get("height", 0) or 0)
        if section_width <= 0 or section_height <= 0:
            return False
        section_area = section_width * section_height
        overflow_x_threshold = max(24.0, section_width * 0.04)
        overflow_y_threshold = max(24.0, section_height * 0.04)
        for asset in self._iter_assets(section.get("children", [])):
            if ensure_text(asset.get("purpose")).lower() != "content":
                continue
            asset_bounds = asset.get("bounds", {}) or {}
            asset_left = float(asset_bounds.get("x", 0) or 0)
            asset_top = float(asset_bounds.get("y", 0) or 0)
            asset_width = float(asset_bounds.get("width", 0) or 0)
            asset_height = float(asset_bounds.get("height", 0) or 0)
            if asset_width <= 0 or asset_height <= 0:
                continue
            if asset_width * asset_height < section_area * 0.08:
                continue
            asset_right = asset_left + asset_width
            asset_bottom = asset_top + asset_height
            overflow_left = max(0.0, -asset_left)
            overflow_top = max(0.0, -asset_top)
            overflow_right = max(0.0, asset_right - section_width)
            overflow_bottom = max(0.0, asset_bottom - section_height)
            if (
                max(overflow_left, overflow_right) >= overflow_x_threshold
                or max(overflow_top, overflow_bottom) >= overflow_y_threshold
            ):
                return True
        return False

    def _has_large_decorative_overflow(self, asset: dict[str, Any], section: dict[str, Any]) -> bool:
        section_bounds = section.get("bounds", {}) or {}
        section_left = float(section_bounds.get("x", 0) or 0)
        section_top = float(section_bounds.get("y", 0) or 0)
        section_width = float(section_bounds.get("width", 0) or 0)
        section_height = float(section_bounds.get("height", 0) or 0)
        if section_width <= 0 or section_height <= 0:
            return False
        section_right = section_left + section_width
        section_bottom = section_top + section_height
        section_area = section_width * section_height
        overflow_x_threshold = max(48.0, section_width * 0.12)
        overflow_y_threshold = max(48.0, section_height * 0.12)
        asset_bounds = asset.get("bounds", {}) or {}
        asset_left = float(asset_bounds.get("x", 0) or 0)
        asset_top = float(asset_bounds.get("y", 0) or 0)
        asset_width = float(asset_bounds.get("width", 0) or 0)
        asset_height = float(asset_bounds.get("height", 0) or 0)
        if asset_width <= 0 or asset_height <= 0:
            return False
        asset_right = asset_left + asset_width
        asset_bottom = asset_top + asset_height
        overflow_left = max(0.0, section_left - asset_left)
        overflow_top = max(0.0, section_top - asset_top)
        overflow_right = max(0.0, asset_right - section_right)
        overflow_bottom = max(0.0, asset_bottom - section_bottom)
        if (
            max(overflow_left, overflow_right) < overflow_x_threshold
            and max(overflow_top, overflow_bottom) < overflow_y_threshold
        ):
            return False
        if asset_width * asset_height < section_area * 0.12:
            return False
        return True

    def _asset_rules(self, asset: dict[str, Any], *, order: int, stack_override: str = "") -> list[str]:
        if asset.get("render") is False:
            return []
        class_name = ensure_text(asset.get("class_name"))
        if not class_name:
            return []
        bounds = asset.get("bounds", {})
        purpose = ensure_text(asset.get("purpose")).strip().lower()
        z_index = self._asset_z_index(asset, order, stack_override=stack_override)
        lines = [
            "",
            f".{class_name} {{",
            *self._hidden_lines(asset),
            *self._absolute_box_rules(bounds),
            f"  z-index: {z_index};",
        ]
        style_css = ensure_text(asset.get("style_css"))
        if style_css:
            for declaration in self._split_css(style_css):
                lines.append(f"  {declaration}")
        if purpose == "background":
            public_path = ensure_text(asset.get("css_public_path") or asset.get("public_path")).replace('"', '\\"')
            if public_path and asset.get("render_mode") != "shape" and asset.get("format") != "shape":
                lines.append(f'  background-image: url("{public_path}");')
                lines.append("  background-position: 0 0;")
                lines.append("  background-repeat: no-repeat;")
                lines.append("  background-size: 100% 100%;")
        lines.append("}")
        return lines

    def _asset_z_index(self, asset: dict[str, Any], order: int, *, stack_override: str = "") -> int:
        if self._is_explicit_parent_background(asset):
            return 0
        purpose = ensure_text(asset.get("purpose")).lower()
        if stack_override == "background-bleed" and purpose == "decorative":
            return min(45, 5 + order)
        if stack_override == "background-local" and purpose == "background":
            return 180 + order
        if stack_override == "panel-overlay" and purpose == "decorative":
            return 220 + order
        if stack_override == "foreground-overlay" and purpose == "decorative":
            return 350 + order
        if purpose == "decorative" and self._is_shadow_shape(asset):
            return 40 + order
        if purpose == "background":
            return 50 + order
        if purpose == "foreground":
            return 500 + order
        if purpose in {"decorative", "mask"}:
            return 100 + order
        if purpose == "icon":
            return 300 + order
        return 250 + order

    def _is_explicit_parent_background(self, asset: dict[str, Any]) -> bool:
        asset_name = ensure_text(asset.get("name") or asset.get("nodeId") or asset.get("id"))
        if name_has_prefix(asset_name, ("bg",)):
            return True
        class_name = ensure_text(asset.get("class_name"))
        if class_name.startswith("asset-"):
            class_name = class_name[6:]
        return name_has_prefix(class_name, ("bg",))

    def _infer_asset_stack_overrides(self, section: dict[str, Any]) -> dict[str, str]:
        """Tente de corriger quelques problèmes récurrents de couches.

        Figma et notre sortie HTML ne partagent pas exactement le même modèle de
        stacking. Ici on applique donc des heuristiques locales, limitées à la
        section, pour remettre certains backgrounds ou overlays dans un ordre
        plus proche du rendu attendu.
        """

        overrides: dict[str, str] = {}
        section_assets = list(self._iter_assets(section.get("children", [])))
        content_assets = [
            asset for asset in section_assets if ensure_text(asset.get("purpose")).lower() == "content"
        ]
        prior_content_assets: list[dict[str, Any]] = []
        prior_backdrop_assets: list[dict[str, Any]] = []
        local_background_assets: list[dict[str, Any]] = []
        metadata = section.get("metadata", {}) or {}
        source_node_type = ensure_text(metadata.get("sourceNodeType")).upper()
        for asset in section_assets:
            purpose = ensure_text(asset.get("purpose")).lower()
            if purpose == "content":
                prior_content_assets.append(asset)
                continue
            if purpose == "background":
                asset_id = ensure_text(asset.get("id") or asset.get("node_id"))
                if asset_id and any(
                    self._should_promote_local_background(asset, other, section) for other in prior_backdrop_assets
                ):
                    overrides[asset_id] = "background-local"
                    local_background_assets.append(asset)
                    for prior_asset in prior_backdrop_assets:
                        prior_asset_id = ensure_text(prior_asset.get("id") or prior_asset.get("node_id"))
                        prior_purpose = ensure_text(prior_asset.get("purpose")).lower()
                        if not prior_asset_id or prior_purpose != "decorative":
                            continue
                        if self._should_promote_panel_overlay(prior_asset, asset):
                            overrides[prior_asset_id] = "panel-overlay"
                prior_backdrop_assets.append(asset)
                continue
            if purpose != "decorative":
                continue
            if source_node_type == "GROUP" and self._has_large_decorative_overflow(asset, section):
                asset_id = ensure_text(asset.get("id") or asset.get("node_id"))
                if asset_id:
                    overrides[asset_id] = "background-bleed"
                prior_backdrop_assets.append(asset)
                continue
            asset_id = ensure_text(asset.get("id") or asset.get("node_id"))
            if asset_id and any(self._should_promote_panel_overlay(asset, panel) for panel in local_background_assets):
                overrides[asset_id] = "panel-overlay"
                prior_backdrop_assets.append(asset)
                continue
            if any(
                self._bounds_overlap_as_overlay(asset.get("bounds", {}), other.get("bounds", {}))
                for other in content_assets
            ) or any(
                self._bounds_overlap_as_large_overlay(asset.get("bounds", {}), other.get("bounds", {}))
                for other in prior_content_assets
            ):
                if asset_id:
                    overrides[asset_id] = "foreground-overlay"
            prior_backdrop_assets.append(asset)
        return overrides

    def _iter_assets(self, nodes: list[dict[str, Any]]):
        for node in nodes:
            if node.get("kind") == "asset":
                asset = node.get("asset", {})
                if asset:
                    yield asset
            yield from self._iter_assets(node.get("children", []))

    def _is_shadow_shape(self, asset: dict[str, Any]) -> bool:
        render_mode = ensure_text(asset.get("render_mode") or asset.get("renderMode")).lower()
        style = asset.get("style", {}) or {}
        return render_mode == "shape" and bool(style.get("boxShadow"))

    def _should_promote_local_background(
        self,
        asset: dict[str, Any],
        other: dict[str, Any],
        section: dict[str, Any],
    ) -> bool:
        asset_bounds = asset.get("bounds", {}) or {}
        other_bounds = other.get("bounds", {}) or {}
        if not self._bounds_overlap_as_overlay(asset_bounds, other_bounds):
            return False
        section_bounds = section.get("bounds", {}) or {}
        section_area = max(
            float(section_bounds.get("width", 0) or 0) * float(section_bounds.get("height", 0) or 0),
            1.0,
        )
        asset_area = float(asset_bounds.get("width", 0) or 0) * float(asset_bounds.get("height", 0) or 0)
        other_area = float(other_bounds.get("width", 0) or 0) * float(other_bounds.get("height", 0) or 0)
        if asset_area <= 0 or other_area <= 0:
            return False
        if asset_area >= other_area:
            return False
        if other_area / asset_area < 1.35:
            return False
        return (asset_area / section_area) <= 0.22 and (other_area / section_area) >= 0.18

    def _should_promote_panel_overlay(
        self,
        asset: dict[str, Any],
        panel: dict[str, Any],
    ) -> bool:
        asset_bounds = asset.get("bounds", {}) or {}
        panel_bounds = panel.get("bounds", {}) or {}
        if not self._bounds_overlap_as_overlay(asset_bounds, panel_bounds):
            return False
        asset_area = float(asset_bounds.get("width", 0) or 0) * float(asset_bounds.get("height", 0) or 0)
        panel_area = float(panel_bounds.get("width", 0) or 0) * float(panel_bounds.get("height", 0) or 0)
        if asset_area <= 0 or panel_area <= 0:
            return False
        if asset_area / panel_area > 0.65:
            return False
        tolerance_x = float(panel_bounds.get("width", 0) or 0) * 0.08
        tolerance_y = float(panel_bounds.get("height", 0) or 0) * 0.08
        return self._is_bounds_mostly_within(asset_bounds, panel_bounds, tolerance_x=tolerance_x, tolerance_y=tolerance_y)

    def _is_bounds_mostly_within(
        self,
        inner: dict[str, Any],
        outer: dict[str, Any],
        *,
        tolerance_x: float = 0.0,
        tolerance_y: float = 0.0,
    ) -> bool:
        inner_left = float(inner.get("x", 0) or 0)
        inner_top = float(inner.get("y", 0) or 0)
        inner_right = inner_left + float(inner.get("width", 0) or 0)
        inner_bottom = inner_top + float(inner.get("height", 0) or 0)
        outer_left = float(outer.get("x", 0) or 0) - tolerance_x
        outer_top = float(outer.get("y", 0) or 0) - tolerance_y
        outer_right = float(outer.get("x", 0) or 0) + float(outer.get("width", 0) or 0) + tolerance_x
        outer_bottom = float(outer.get("y", 0) or 0) + float(outer.get("height", 0) or 0) + tolerance_y
        return (
            inner_left >= outer_left
            and inner_top >= outer_top
            and inner_right <= outer_right
            and inner_bottom <= outer_bottom
        )

    def _bounds_overlap_as_overlay(self, first: dict[str, Any], second: dict[str, Any]) -> bool:
        first_left = float(first.get("x", 0) or 0)
        first_top = float(first.get("y", 0) or 0)
        first_width = float(first.get("width", 0) or 0)
        first_height = float(first.get("height", 0) or 0)
        second_left = float(second.get("x", 0) or 0)
        second_top = float(second.get("y", 0) or 0)
        second_width = float(second.get("width", 0) or 0)
        second_height = float(second.get("height", 0) or 0)
        if min(first_width, first_height, second_width, second_height) <= 0:
            return False
        overlap_width = min(first_left + first_width, second_left + second_width) - max(first_left, second_left)
        overlap_height = min(first_top + first_height, second_top + second_height) - max(first_top, second_top)
        if overlap_width <= 0 or overlap_height <= 0:
            return False
        overlap_area = overlap_width * overlap_height
        first_area = first_width * first_height
        second_area = second_width * second_height
        if first_area > second_area * 1.8:
            return False
        smaller_area = min(first_width * first_height, second_width * second_height)
        return overlap_area / max(smaller_area, 1.0) >= 0.08

    def _bounds_overlap_as_large_overlay(self, first: dict[str, Any], second: dict[str, Any]) -> bool:
        first_left = float(first.get("x", 0) or 0)
        first_top = float(first.get("y", 0) or 0)
        first_width = float(first.get("width", 0) or 0)
        first_height = float(first.get("height", 0) or 0)
        second_left = float(second.get("x", 0) or 0)
        second_top = float(second.get("y", 0) or 0)
        second_width = float(second.get("width", 0) or 0)
        second_height = float(second.get("height", 0) or 0)
        if min(first_width, first_height, second_width, second_height) <= 0:
            return False
        overlap_width = min(first_left + first_width, second_left + second_width) - max(first_left, second_left)
        overlap_height = min(first_top + first_height, second_top + second_height) - max(first_top, second_top)
        if overlap_width <= 0 or overlap_height <= 0:
            return False
        overlap_area = overlap_width * overlap_height
        first_area = first_width * first_height
        second_area = second_width * second_height
        if first_area <= second_area * 1.8:
            return False
        if first_area > second_area * 4.5:
            return False
        return overlap_area / max(second_area, 1.0) >= 0.55

    def _absolute_box_rules(self, bounds: dict[str, Any], *, include_height: bool = True) -> list[str]:
        left = float(bounds.get("x", 0) or 0)
        top = float(bounds.get("y", 0) or 0)
        width = float(bounds.get("width", 0) or 0)
        height = float(bounds.get("height", 0) or 0)
        lines = [
            f"  left: {left:.2f}px;",
            f"  top: {top:.2f}px;",
        ]
        if width > 0:
            lines.append(f"  width: {width:.2f}px;")
        if include_height and height > 0:
            lines.append(f"  height: {height:.2f}px;")
        return lines

    def _split_css(self, style_css: str) -> list[str]:
        declarations = []
        for item in style_css.split(";"):
            stripped = item.strip()
            if not stripped:
                continue
            declarations.append(f"{stripped};")
        return declarations

    def _responsive_override_lines(self, page_data: dict[str, Any]) -> list[str]:
        responsive = as_mapping(page_data.get("responsive"))
        page = as_mapping(page_data.get("page"))
        page_slug = ensure_text(page.get("slug")).strip()
        raw_variants = responsive.get("variants", [])
        if not page_slug or not isinstance(raw_variants, list):
            return []

        variants: list[tuple[int, dict[str, Any]]] = []
        for raw_variant in raw_variants:
            variant = as_mapping(raw_variant)
            try:
                width = int(variant.get("width") or 0)
            except (TypeError, ValueError):
                width = 0
            variant_page = as_mapping(variant.get("page"))
            if width <= 0 or not variant_page:
                continue
            variants.append((width, variant_page))
        if not variants:
            return []

        merged_sections = [section for section in page_data.get("sections", []) if isinstance(section, dict)]
        lines: list[str] = []
        for width, variant_page in sorted(variants, key=lambda item: item[0], reverse=True):
            media_lines: list[str] = []
            media_lines.extend(self._responsive_page_shell_lines(page_slug, variant_page))

            variant_section_lines = self._responsive_variant_section_lines(variant_page)
            if variant_section_lines:
                media_lines.extend(["", *variant_section_lines])

            form_control_lines = self._responsive_form_control_override_lines(variant_page)
            if form_control_lines:
                media_lines.extend(["", *form_control_lines])

            visibility_lines = self._responsive_visibility_lines(merged_sections, width)
            if visibility_lines:
                media_lines.extend(["", *visibility_lines])

            if not media_lines:
                continue
            lines.extend(
                [
                    "",
                    f"@media (max-width: {width}px) {{",
                    *self._indent_lines(media_lines, level=1),
                    "}",
                ]
            )
        return lines

    def _responsive_page_shell_lines(self, page_slug: str, variant_page: dict[str, Any]) -> list[str]:
        page = as_mapping(variant_page.get("page"))
        sections = [section for section in variant_page.get("sections", []) if isinstance(section, dict)]
        page_width, page_height, _, _ = self._page_geometry(page, sections)
        return [
            f".page.page--{page_slug} {{",
            f"  --page-max-width: {page_width}px;",
            "  width: var(--page-max-width);",
            "  max-width: none;",
            f"  min-height: {page_height}px;" if page_height else "  min-height: 100vh;",
            "}",
        ]

    def _responsive_variant_section_lines(self, variant_page: dict[str, Any]) -> list[str]:
        page = as_mapping(variant_page.get("page"))
        sections = [section for section in variant_page.get("sections", []) if isinstance(section, dict)]
        if not sections:
            return []
        page_width, _, page_origin_x, page_origin_y = self._page_geometry(page, sections)
        lines: list[str] = []
        flow_cursor_bottom = 0.0
        for section in sections:
            section_lines, flow_cursor_bottom = self._section_rules(
                section,
                page_width,
                page_origin_x,
                page_origin_y,
                flow_cursor_bottom=flow_cursor_bottom,
            )
            lines.extend(section_lines)
        return lines

    def _responsive_form_control_override_lines(self, variant_page: dict[str, Any]) -> list[str]:
        lines: list[str] = []
        for section in variant_page.get("sections", []):
            if not isinstance(section, dict):
                continue
            for node in section.get("children", []):
                lines.extend(self._responsive_node_form_control_override_lines(node))
        return lines

    def _responsive_node_form_control_override_lines(self, node: dict[str, Any]) -> list[str]:
        if not isinstance(node, dict):
            return []
        lines: list[str] = []
        if node.get("kind") == "container":
            control = as_mapping(node.get("form_control"))
            if control:
                class_name = ensure_text(control.get("class_name")).strip()
                bounds = as_mapping(control.get("bounds"))
                if class_name and bounds:
                    left = float(bounds.get("x", 0) or 0)
                    top = float(bounds.get("y", 0) or 0)
                    width = float(bounds.get("width", 0) or 0)
                    height = float(bounds.get("height", 0) or 0)
                    control_lines = [
                        "",
                        f".{class_name} {{",
                        "  position: absolute !important;",
                        f"  left: {left:.2f}px !important;",
                        f"  top: {top:.2f}px !important;",
                    ]
                    if width > 0:
                        control_lines.append(f"  width: {width:.2f}px !important;")
                    if height > 0:
                        control_lines.append(f"  height: {height:.2f}px !important;")
                    control_lines.append("}")
                    lines.extend(control_lines)
            for child in node.get("children", []):
                lines.extend(self._responsive_node_form_control_override_lines(child))
        return lines

    def _responsive_visibility_lines(self, merged_sections: list[dict[str, Any]], width: int) -> list[str]:
        lines: list[str] = []
        for section in merged_sections:
            lines.extend(self._responsive_item_visibility_lines(section, width))
        return lines

    def _responsive_item_visibility_lines(self, item: dict[str, Any], width: int) -> list[str]:
        selector = self._responsive_selector(item)
        lines: list[str] = []
        raw_present_widths = item.get("responsive_present_widths", [])
        present_widths = {
            int(value)
            for value in raw_present_widths
            if isinstance(value, int) or ensure_text(value).isdigit()
        }
        default_hidden = bool(item.get("responsive_default_hidden"))
        if selector and present_widths:
            if width not in present_widths:
                lines.extend(
                    [
                        f"{selector} {{",
                        "  display: none !important;",
                        "}",
                    ]
                )
                return lines
            if default_hidden:
                lines.extend(
                    [
                        f"{selector} {{",
                        "  display: block !important;",
                        "}",
                    ]
                )
        for child in item.get("children", []):
            if isinstance(child, dict):
                lines.extend(self._responsive_item_visibility_lines(child, width))
        return lines

    def _responsive_selector(self, item: dict[str, Any]) -> str:
        if not isinstance(item, dict):
            return ""
        if item.get("kind") == "text":
            text = as_mapping(item.get("text"))
            class_name = ensure_text(text.get("class_name")).strip()
        elif item.get("kind") == "asset":
            asset = as_mapping(item.get("asset"))
            class_name = ensure_text(asset.get("class_name")).strip()
        else:
            class_name = ensure_text(item.get("class_name")).strip()
        if not class_name:
            return ""
        return f".{class_name}"

    def _hidden_lines(self, item: dict[str, Any]) -> list[str]:
        if not bool(item.get("responsive_default_hidden")):
            return []
        return ["  display: none;"]

    def _indent_lines(self, lines: list[str], *, level: int) -> list[str]:
        indentation = "  " * max(level, 0)
        return [f"{indentation}{line}" if line else "" for line in lines]
