from __future__ import annotations

from typing import Any

from .._shared import ensure_text, extract_scalar_token, flatten_token_map, slugify, style_map_to_css


class CssGenerator:
    def generate(self, page_data: dict[str, Any]) -> str:
        page = page_data.get("page", {})
        sections = page_data.get("sections", [])
        tokens = page_data.get("tokens", {})
        page_width = int(float(page.get("width", 0) or 0)) or 1440
        page_height = int(float(page.get("height", 0) or 0))
        lines = [
            *self._font_imports(page_data),
            "/* Generated by figma2hugo. */",
            "",
            ":root {",
            f"  --page-max-width: {page_width}px;",
            "  --surface-page: #ffffff;",
            "  --text-color: #171717;",
        ]
        lines.extend(self._token_variables("color", tokens.get("colors", {})))
        lines.extend(self._token_variables("space", tokens.get("spacing", {})))
        lines.extend(self._token_variables("font", tokens.get("typography", {})))
        lines.extend(self._token_variables("shadow", tokens.get("shadows", {})))
        lines.extend(self._token_variables("radius", tokens.get("radii", {})))
        lines.append("}")
        lines.extend(
            [
                "",
                "*,",
                "*::before,",
                "*::after {",
                "  box-sizing: border-box;",
                "}",
                "",
                "html {",
                "  font-size: 16px;",
                "  scroll-behavior: smooth;",
                "}",
                "",
                "body {",
                "  margin: 0;",
                f"  min-width: {page_width}px;",
                "  min-height: 100vh;",
                '  font-family: var(--font-body-family, "Segoe UI", sans-serif);',
                "  color: var(--text-color);",
                "  background: var(--surface-page);",
                "  overflow-x: auto;",
                "}",
                "",
                "img {",
                "  display: block;",
                "}",
                "",
                "a {",
                "  color: inherit;",
                "  text-decoration: none;",
                "}",
                "",
                ".page {",
                "  position: relative;",
                "  width: var(--page-max-width);",
                f"  min-height: {page_height}px;" if page_height else "  min-height: 100vh;",
                "  margin: 0 auto;",
                "}",
                "",
                ".page-main {",
                "  display: block;",
                "}",
                "",
                ".page-section {",
                "  position: relative;",
                "  width: var(--page-max-width);",
                "  margin: 0 auto;",
                "  padding: 0;",
                "  overflow: visible;",
                "}",
                "",
                ".page-section__inner {",
                "  position: relative;",
                "  width: var(--page-max-width);",
                "  margin: 0 auto;",
                "  overflow: visible;",
                "}",
                "",
                ".content-node,",
                ".content-text,",
                ".content-asset {",
                "  position: absolute;",
                "  margin: 0;",
                "}",
                "",
                ".content-text {",
                "  max-width: none;",
                "  transform-origin: top left;",
                "}",
                "",
                ".content-text span {",
                "  white-space: nowrap;",
                "}",
                "",
                ".content-asset {",
                "  line-height: 0;",
                "}",
                "",
                ".content-asset img {",
                "  width: 100%;",
                "  height: 100%;",
                "  object-fit: contain;",
                "}",
                "",
                ".is-decorative {",
                "  pointer-events: none;",
                "  user-select: none;",
                "}",
            ]
        )
        for section in sections:
            lines.extend(self._section_rules(section, page_width))
        return "\n".join(lines) + "\n"

    def _font_imports(self, page_data: dict[str, Any]) -> list[str]:
        fonts = self._collect_font_families(page_data)
        lines: list[str] = []
        if "Inter" in fonts:
            lines.append('@import url("https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,100..900;1,100..900&display=swap");')
            lines.append("")
        return lines

    def _collect_font_families(self, page_data: dict[str, Any]) -> set[str]:
        families: set[str] = set()
        for text in page_data.get("texts", {}).values():
            style = text.get("style", {})
            family = ensure_text(style.get("fontFamily")).strip()
            if family:
                families.add(family)
            for segment in text.get("segments", []):
                style_text = ensure_text(segment.get("style"))
                marker = 'font-family: "'
                if marker in style_text:
                    rest = style_text.split(marker, 1)[1]
                    families.add(rest.split('"', 1)[0])
                elif "font-family:" in style_text:
                    rest = style_text.split("font-family:", 1)[1].split(";", 1)[0]
                    families.add(rest.replace('"', "").replace(", sans-serif", "").strip())
        return {family for family in families if family}

    def _token_variables(self, prefix: str, token_map: Any) -> list[str]:
        lines: list[str] = []
        for token_name, token_value in flatten_token_map(prefix, token_map):
            if not token_name:
                continue
            scalar = extract_scalar_token(token_value)
            if not scalar and isinstance(token_value, dict):
                if prefix == "font":
                    token_slug = slugify(token_name, "token")
                    family = ensure_text(token_value.get("fontFamily"))
                    size = ensure_text(token_value.get("fontSize"))
                    weight = ensure_text(token_value.get("fontWeight"))
                    line_height = ensure_text(token_value.get("lineHeight"))
                    if family:
                        lines.append(f'  --{token_slug}-family: "{family}";')
                    if size:
                        lines.append(f"  --{token_slug}-size: {size if any(ch.isalpha() for ch in size) else f'{size}px'};")
                    if weight:
                        lines.append(f"  --{token_slug}-weight: {weight};")
                    if line_height:
                        lines.append(
                            f"  --{token_slug}-line-height: {line_height if any(ch.isalpha() for ch in line_height) else line_height};"
                        )
                continue
            if scalar:
                token_slug = slugify(token_name, "token")
                lines.append(f"  --{token_slug}: {scalar};")
        return lines

    def _section_rules(self, section: dict[str, Any], page_width: int) -> list[str]:
        section_class = section.get("class_name", "")
        bounds = section.get("bounds", {})
        section_height = int(float(bounds.get("height", 0) or 0))
        section_width = int(float(bounds.get("width", 0) or 0))
        asset_stack_overrides = self._infer_asset_stack_overrides(section.get("children", []))
        lines = [
            "",
            f"/* Section: {section.get('name', section.get('id', 'section'))} */",
            f".{section_class} {{",
            f"  min-height: {section_height}px;" if section_height else "  min-height: 0;",
            "}",
            "",
            f".{section_class} .page-section__inner {{",
            f"  height: {section_height}px;" if section_height else "  height: auto;",
                f"  width: {max(page_width, section_width)}px;" if section_width else f"  width: {page_width}px;",
            "}",
        ]
        for index, node in enumerate(section.get("children", [])):
            lines.extend(self._node_rules(node, order=index, asset_stack_overrides=asset_stack_overrides))
        return lines

    def _node_rules(self, node: dict[str, Any], *, order: int, asset_stack_overrides: dict[str, str]) -> list[str]:
        kind = node.get("kind")
        if kind == "text":
            return self._text_rules(node.get("text", {}), order=order)
        if kind == "asset":
            asset = node.get("asset", {})
            asset_id = ensure_text(asset.get("id") or asset.get("node_id"))
            return self._asset_rules(
                asset,
                order=order,
                stack_override=asset_stack_overrides.get(asset_id, ""),
            )
        class_name = ensure_text(node.get("class_name"))
        if not class_name:
            return []
        bounds = node.get("bounds", {})
        lines = [
            "",
            f".{class_name} {{",
            *self._absolute_box_rules(bounds),
            f"  z-index: {10 + order};",
            "}",
        ]
        for child_index, child in enumerate(node.get("children", [])):
            lines.extend(self._node_rules(child, order=child_index, asset_stack_overrides=asset_stack_overrides))
        return lines

    def _text_rules(self, text: dict[str, Any], *, order: int) -> list[str]:
        class_name = ensure_text(text.get("class_name"))
        if not class_name:
            return []
        bounds = text.get("bounds", {})
        style_css = ensure_text(text.get("style_css"))
        white_space = "nowrap" if text.get("hard_breaks") or text.get("nowrap") else "normal"
        lines = [
            "",
            f".{class_name} {{",
            *self._absolute_box_rules(bounds),
            f"  white-space: {white_space};",
            f"  z-index: {400 + order};",
        ]
        if style_css:
            for declaration in self._split_css(style_css):
                lines.append(f"  {declaration}")
        lines.append("}")
        return lines

    def _asset_rules(self, asset: dict[str, Any], *, order: int, stack_override: str = "") -> list[str]:
        if asset.get("render") is False:
            return []
        class_name = ensure_text(asset.get("class_name"))
        if not class_name:
            return []
        bounds = asset.get("bounds", {})
        z_index = self._asset_z_index(asset, order, stack_override=stack_override)
        return [
            "",
            f".{class_name} {{",
            *self._absolute_box_rules(bounds),
            f"  z-index: {z_index};",
            "}",
        ]

    def _asset_z_index(self, asset: dict[str, Any], order: int, *, stack_override: str = "") -> int:
        purpose = ensure_text(asset.get("purpose")).lower()
        if stack_override == "foreground-overlay" and purpose == "decorative":
            return 350 + order
        if purpose == "background":
            return 50 + order
        if purpose == "foreground":
            return 350 + order
        if purpose in {"decorative", "mask"}:
            return 100 + order
        if purpose == "icon":
            return 300 + order
        return 250 + order

    def _infer_asset_stack_overrides(self, nodes: list[dict[str, Any]]) -> dict[str, str]:
        overrides: dict[str, str] = {}
        prior_content_assets: list[dict[str, Any]] = []
        for asset in self._iter_assets(nodes):
            purpose = ensure_text(asset.get("purpose")).lower()
            if purpose == "content":
                prior_content_assets.append(asset)
                continue
            if purpose != "decorative":
                continue
            if any(self._bounds_overlap_as_overlay(asset.get("bounds", {}), other.get("bounds", {})) for other in prior_content_assets):
                asset_id = ensure_text(asset.get("id") or asset.get("node_id"))
                if asset_id:
                    overrides[asset_id] = "foreground-overlay"
        return overrides

    def _iter_assets(self, nodes: list[dict[str, Any]]):
        for node in nodes:
            if node.get("kind") == "asset":
                asset = node.get("asset", {})
                if asset:
                    yield asset
            yield from self._iter_assets(node.get("children", []))

    def _bounds_overlap_as_overlay(self, first: dict[str, Any], second: dict[str, Any]) -> bool:
        first_left = float(first.get("x", 0) or 0)
        first_top = float(first.get("y", 0) or 0)
        first_width = float(first.get("width", 0) or 0)
        first_height = float(first.get("height", 0) or 0)
        second_left = float(second.get("x", 0) or 0)
        second_top = float(second.get("y", 0) or 0)
        second_width = float(second.get("width", 0) or 0)
        second_height = float(second.get("height", 0) or 0)
        if min(first_width, first_height, second_width, second_height) <= 0:
            return False
        overlap_width = min(first_left + first_width, second_left + second_width) - max(first_left, second_left)
        overlap_height = min(first_top + first_height, second_top + second_height) - max(first_top, second_top)
        if overlap_width <= 0 or overlap_height <= 0:
            return False
        overlap_area = overlap_width * overlap_height
        smaller_area = min(first_width * first_height, second_width * second_height)
        return overlap_area / max(smaller_area, 1.0) >= 0.08

    def _absolute_box_rules(self, bounds: dict[str, Any]) -> list[str]:
        left = float(bounds.get("x", 0) or 0)
        top = float(bounds.get("y", 0) or 0)
        width = float(bounds.get("width", 0) or 0)
        height = float(bounds.get("height", 0) or 0)
        lines = [
            f"  left: {left:.2f}px;",
            f"  top: {top:.2f}px;",
        ]
        if width > 0:
            lines.append(f"  width: {width:.2f}px;")
        if height > 0:
            lines.append(f"  min-height: {height:.2f}px;")
        return lines

    def _split_css(self, style_css: str) -> list[str]:
        declarations = []
        for item in style_css.split(";"):
            stripped = item.strip()
            if not stripped:
                continue
            declarations.append(f"{stripped};")
        return declarations
