from __future__ import annotations

from typing import Any

from .._shared import ensure_text, extract_scalar_token, flatten_token_map, slugify, style_map_to_css


class CssGenerator:
    def generate(self, page_data: dict[str, Any]) -> str:
        page = page_data.get("page", {})
        sections = page_data.get("sections", [])
        tokens = page_data.get("tokens", {})
        page_width, page_height, page_origin_x, page_origin_y = self._page_geometry(page, sections)
        lines = [
            *self._font_imports(page_data),
            "/* Generated by figma2hugo. */",
            "",
            ":root {",
            f"  --page-max-width: {page_width}px;",
            "  --surface-page: #ffffff;",
            "  --text-color: #171717;",
        ]
        lines.extend(self._token_variables("color", tokens.get("colors", {})))
        lines.extend(self._token_variables("space", tokens.get("spacing", {})))
        lines.extend(self._token_variables("font", tokens.get("typography", {})))
        lines.extend(self._token_variables("shadow", tokens.get("shadows", {})))
        lines.extend(self._token_variables("radius", tokens.get("radii", {})))
        lines.append("}")
        lines.extend(
            [
                "",
                "*,",
                "*::before,",
                "*::after {",
                "  box-sizing: border-box;",
                "}",
                "",
                "html {",
                "  font-size: 16px;",
                "  scroll-behavior: smooth;",
                "}",
                "",
                "body {",
                "  margin: 0;",
                f"  min-width: {page_width}px;",
                "  min-height: 100vh;",
                '  font-family: var(--font-body-family, "Segoe UI", sans-serif);',
                "  color: var(--text-color);",
                "  background: var(--surface-page);",
                "  overflow-x: hidden;",
                "}",
                "",
                "img {",
                "  display: block;",
                "}",
                "",
                "a {",
                "  color: inherit;",
                "  text-decoration: none;",
                "}",
                "",
                ".page {",
                "  position: relative;",
                "  width: var(--page-max-width);",
                f"  min-height: {page_height}px;" if page_height else "  min-height: 100vh;",
                "  margin: 0 auto;",
                "}",
                "",
                ".page-main {",
                "  display: block;",
                "}",
                "",
                ".page-section {",
                "  position: absolute;",
                "  left: 0;",
                "  top: 0;",
                "  padding: 0;",
                "  overflow: visible;",
                "}",
                "",
                ".page-section__inner {",
                "  position: relative;",
                "  overflow: visible;",
                "}",
                "",
                ".content-node,",
                ".content-text,",
                ".content-asset {",
                "  position: absolute;",
                "  margin: 0;",
                "}",
                "",
                ".content-text {",
                "  max-width: none;",
                "  transform-origin: top left;",
                "}",
                "",
                ".content-text span {",
                "  white-space: inherit;",
                "}",
                "",
                ".content-asset {",
                "  line-height: 0;",
                "}",
                "",
                ".content-asset img {",
                "  width: 100%;",
                "  height: 100%;",
                "  object-fit: contain;",
                "}",
                "",
                ".is-decorative {",
                "  pointer-events: none;",
                "  user-select: none;",
                "}",
            ]
        )
        for section in sections:
            lines.extend(self._section_rules(section, page_width, page_origin_x, page_origin_y))
        return "\n".join(lines) + "\n"

    def _font_imports(self, page_data: dict[str, Any]) -> list[str]:
        fonts = self._collect_font_families(page_data)
        google_font_params = {
            "Inter": "family=Inter:ital,wght@0,100..900;1,100..900",
            "Roboto": "family=Roboto:ital,wght@0,100..900;1,100..900",
            "Roboto Slab": "family=Roboto+Slab:wght@100..900",
        }
        lines: list[str] = []
        selected = [google_font_params[font] for font in sorted(fonts) if font in google_font_params]
        if selected:
            lines.append(f'@import url("https://fonts.googleapis.com/css2?{"&".join(selected)}&display=swap");')
            lines.append("")
        return lines

    def _page_geometry(self, page: dict[str, Any], sections: list[dict[str, Any]]) -> tuple[int, int, float, float]:
        raw_width = int(float(page.get("width", 0) or 0))
        raw_height = int(float(page.get("height", 0) or 0))
        if not sections:
            return (raw_width or 1440, raw_height, 0.0, 0.0)

        section_bounds = [section.get("bounds", {}) or {} for section in sections]
        lefts = [float(bounds.get("x", 0) or 0) for bounds in section_bounds]
        tops = [float(bounds.get("y", 0) or 0) for bounds in section_bounds]
        rights = [
            float(bounds.get("x", 0) or 0) + float(bounds.get("width", 0) or 0)
            for bounds in section_bounds
        ]
        bottoms = [
            float(bounds.get("y", 0) or 0) + float(bounds.get("height", 0) or 0)
            for bounds in section_bounds
        ]

        origin_x = min(lefts)
        origin_y = min(tops)
        extent_width = max(0.0, max(rights) - origin_x)
        extent_height = max(0.0, max(bottoms) - origin_y)
        page_width = max(raw_width or 0, int(round(extent_width)) or 0) or 1440
        page_height = max(raw_height or 0, int(round(extent_height)) or 0)
        return page_width, page_height, origin_x, origin_y

    def _collect_font_families(self, page_data: dict[str, Any]) -> set[str]:
        families: set[str] = set()
        for text in page_data.get("texts", {}).values():
            style = text.get("style", {})
            family = ensure_text(style.get("fontFamily")).strip()
            if family:
                families.add(family)
            for segment in text.get("segments", []):
                style_text = ensure_text(segment.get("style"))
                marker = 'font-family: "'
                if marker in style_text:
                    rest = style_text.split(marker, 1)[1]
                    families.add(rest.split('"', 1)[0])
                elif "font-family:" in style_text:
                    rest = style_text.split("font-family:", 1)[1].split(";", 1)[0]
                    families.add(rest.replace('"', "").replace(", sans-serif", "").strip())
        return {family for family in families if family}

    def _token_variables(self, prefix: str, token_map: Any) -> list[str]:
        lines: list[str] = []
        for token_name, token_value in flatten_token_map(prefix, token_map):
            if not token_name:
                continue
            scalar = extract_scalar_token(token_value)
            if not scalar and isinstance(token_value, dict):
                if prefix == "font":
                    token_slug = slugify(token_name, "token")
                    family = ensure_text(token_value.get("fontFamily"))
                    size = ensure_text(token_value.get("fontSize"))
                    weight = ensure_text(token_value.get("fontWeight"))
                    line_height = ensure_text(token_value.get("lineHeight"))
                    if family:
                        lines.append(f'  --{token_slug}-family: "{family}";')
                    if size:
                        lines.append(f"  --{token_slug}-size: {size if any(ch.isalpha() for ch in size) else f'{size}px'};")
                    if weight:
                        lines.append(f"  --{token_slug}-weight: {weight};")
                    if line_height:
                        lines.append(
                            f"  --{token_slug}-line-height: {line_height if any(ch.isalpha() for ch in line_height) else line_height};"
                        )
                continue
            if scalar:
                token_slug = slugify(token_name, "token")
                lines.append(f"  --{token_slug}: {scalar};")
        return lines

    def _section_rules(
        self,
        section: dict[str, Any],
        page_width: int,
        page_origin_x: float,
        page_origin_y: float,
    ) -> list[str]:
        section_class = section.get("class_name", "")
        bounds = section.get("bounds", {})
        section_left = float(bounds.get("x", 0) or 0) - page_origin_x
        section_top = float(bounds.get("y", 0) or 0) - page_origin_y
        section_height = int(float(bounds.get("height", 0) or 0))
        section_width = int(float(bounds.get("width", 0) or 0))
        asset_stack_overrides = self._infer_asset_stack_overrides(section)
        lines = [
            "",
            f"/* Section: {section.get('name', section.get('id', 'section'))} */",
            f".{section_class} {{",
            f"  left: {section_left:.2f}px;",
            f"  top: {section_top:.2f}px;",
            f"  width: {section_width}px;" if section_width else f"  width: {page_width}px;",
            f"  height: {section_height}px;" if section_height else "  height: auto;",
            f"  min-height: {section_height}px;" if section_height else "  min-height: 0;",
            "}",
            "",
            f".{section_class} .page-section__inner {{",
            f"  height: {section_height}px;" if section_height else "  height: auto;",
            f"  width: {section_width}px;" if section_width else f"  width: {page_width}px;",
            "}",
        ]
        section_inner_overflow = self._section_inner_overflow(section)
        if section_inner_overflow:
            lines.insert(-1, f"  overflow: {section_inner_overflow};")
        for index, node in enumerate(section.get("children", [])):
            lines.extend(self._node_rules(node, order=index, asset_stack_overrides=asset_stack_overrides))
        return lines

    def _node_rules(self, node: dict[str, Any], *, order: int, asset_stack_overrides: dict[str, str]) -> list[str]:
        kind = node.get("kind")
        if kind == "text":
            return self._text_rules(node.get("text", {}), order=order)
        if kind == "asset":
            asset = node.get("asset", {})
            asset_id = ensure_text(asset.get("id") or asset.get("node_id"))
            return self._asset_rules(
                asset,
                order=order,
                stack_override=asset_stack_overrides.get(asset_id, ""),
            )
        class_name = ensure_text(node.get("class_name"))
        if not class_name:
            return []
        bounds = node.get("bounds", {})
        lines = [
            "",
            f".{class_name} {{",
            *self._absolute_box_rules(bounds),
            f"  z-index: {10 + order};",
            "}",
        ]
        for child_index, child in enumerate(node.get("children", [])):
            lines.extend(self._node_rules(child, order=child_index, asset_stack_overrides=asset_stack_overrides))
        return lines

    def _text_rules(self, text: dict[str, Any], *, order: int) -> list[str]:
        class_name = ensure_text(text.get("class_name"))
        if not class_name:
            return []
        bounds = text.get("bounds", {})
        render_bounds = text.get("render_bounds", {}) or {}
        style_css = ensure_text(text.get("style_css"))
        nowrap = bool(text.get("nowrap"))
        preserve_spaces = bool(text.get("preserve_spaces"))
        white_space = "nowrap" if nowrap else "normal"
        if preserve_spaces and nowrap:
            white_space = "pre"
        lines = [
            "",
            f".{class_name} {{",
            *self._absolute_box_rules(bounds, include_height=False),
            f"  white-space: {white_space};",
            f"  z-index: {400 + order};",
        ]
        preferred_height = self._preferred_text_height(text, bounds, render_bounds)
        if preferred_height > 0:
            lines.append(f"  height: {preferred_height:.2f}px;")
            lines.append("  overflow: hidden;")
        for declaration in self._effective_text_style_declarations(text, style_css):
                lines.append(f"  {declaration}")
        lines.append("}")
        return lines

    def _preferred_text_height(self, text: dict[str, Any], bounds: dict[str, Any], render_bounds: dict[str, Any]) -> float:
        bounds_height = float(bounds.get("height", 0) or 0)
        render_height = float(render_bounds.get("height", 0) or 0)
        if bounds_height > 0:
            if (
                render_height > 0
                and render_height < bounds_height
                and self._has_spacer_breaks(text)
                and not self._has_compact_segment_line_height(text)
            ):
                return render_height
            return bounds_height
        return render_height

    def _has_spacer_breaks(self, text: dict[str, Any]) -> bool:
        value = ensure_text(text.get("value") or text.get("plain_text"))
        normalized = value.replace("\r\n", "\n").replace("\r", "\n")
        return "\n\n" in normalized or normalized.endswith("\n")

    def _has_compact_segment_line_height(self, text: dict[str, Any]) -> bool:
        return self._compact_segment_line_height(text) > 0

    def _compact_segment_line_height(self, text: dict[str, Any]) -> float:
        base_line_height = self._numeric_line_height(text.get("style", {}))
        if base_line_height <= 0:
            return 0.0
        candidate_line_heights: list[float] = []
        for segment in text.get("segments", []):
            segment_line_height = self._numeric_line_height(segment)
            if segment_line_height > 0 and segment_line_height < (base_line_height * 0.85):
                candidate_line_heights.append(segment_line_height)
        if not candidate_line_heights:
            return 0.0
        return min(candidate_line_heights)

    def _numeric_line_height(self, value: Any) -> float:
        if isinstance(value, dict):
            direct = value.get("lineHeight")
            if isinstance(direct, (int, float)):
                return float(direct)
            style_text = ensure_text(value.get("style"))
        else:
            style_text = ensure_text(value)
        if not style_text:
            return 0.0
        for declaration in self._split_css(style_text):
            if not declaration.startswith("line-height:"):
                continue
            raw_value = declaration.split(":", 1)[1].strip().rstrip(";").strip()
            if raw_value.endswith("px"):
                raw_value = raw_value[:-2].strip()
            try:
                return float(raw_value)
            except ValueError:
                return 0.0
        return 0.0

    def _effective_text_style_declarations(self, text: dict[str, Any], style_css: str) -> list[str]:
        declarations = self._split_css(style_css) if style_css else []
        compact_line_height = self._compact_segment_line_height(text)
        if compact_line_height > 0:
            updated: list[str] = []
            replaced = False
            for declaration in declarations:
                if declaration.startswith("line-height:"):
                    updated.append(f"line-height: {compact_line_height:.2f}px;")
                    replaced = True
                else:
                    updated.append(declaration)
            if not replaced:
                updated.append(f"line-height: {compact_line_height:.2f}px;")
            declarations = updated
        if bool(text.get("preserve_spaces")) and bool(text.get("nowrap")):
            adjusted: list[str] = []
            for declaration in declarations:
                if declaration == "text-align: justify;":
                    adjusted.append("text-align: left;")
                else:
                    adjusted.append(declaration)
            declarations = adjusted
        return declarations

    def _section_inner_overflow(self, section: dict[str, Any]) -> str:
        metadata = section.get("metadata", {}) or {}
        if bool(metadata.get("clipsContent")):
            return "hidden"
        if self._has_large_content_overflow(section):
            return "hidden"
        return ""

    def _has_large_content_overflow(self, section: dict[str, Any]) -> bool:
        section_bounds = section.get("bounds", {}) or {}
        section_width = float(section_bounds.get("width", 0) or 0)
        section_height = float(section_bounds.get("height", 0) or 0)
        if section_width <= 0 or section_height <= 0:
            return False
        section_area = section_width * section_height
        overflow_x_threshold = max(24.0, section_width * 0.04)
        overflow_y_threshold = max(24.0, section_height * 0.04)
        for asset in self._iter_assets(section.get("children", [])):
            if ensure_text(asset.get("purpose")).lower() != "content":
                continue
            asset_bounds = asset.get("bounds", {}) or {}
            asset_left = float(asset_bounds.get("x", 0) or 0)
            asset_top = float(asset_bounds.get("y", 0) or 0)
            asset_width = float(asset_bounds.get("width", 0) or 0)
            asset_height = float(asset_bounds.get("height", 0) or 0)
            if asset_width <= 0 or asset_height <= 0:
                continue
            if asset_width * asset_height < section_area * 0.08:
                continue
            asset_right = asset_left + asset_width
            asset_bottom = asset_top + asset_height
            overflow_left = max(0.0, -asset_left)
            overflow_top = max(0.0, -asset_top)
            overflow_right = max(0.0, asset_right - section_width)
            overflow_bottom = max(0.0, asset_bottom - section_height)
            if (
                max(overflow_left, overflow_right) >= overflow_x_threshold
                or max(overflow_top, overflow_bottom) >= overflow_y_threshold
            ):
                return True
        return False

    def _has_large_decorative_overflow(self, asset: dict[str, Any], section: dict[str, Any]) -> bool:
        section_bounds = section.get("bounds", {}) or {}
        section_left = float(section_bounds.get("x", 0) or 0)
        section_top = float(section_bounds.get("y", 0) or 0)
        section_width = float(section_bounds.get("width", 0) or 0)
        section_height = float(section_bounds.get("height", 0) or 0)
        if section_width <= 0 or section_height <= 0:
            return False
        section_right = section_left + section_width
        section_bottom = section_top + section_height
        section_area = section_width * section_height
        overflow_x_threshold = max(48.0, section_width * 0.12)
        overflow_y_threshold = max(48.0, section_height * 0.12)
        asset_bounds = asset.get("bounds", {}) or {}
        asset_left = float(asset_bounds.get("x", 0) or 0)
        asset_top = float(asset_bounds.get("y", 0) or 0)
        asset_width = float(asset_bounds.get("width", 0) or 0)
        asset_height = float(asset_bounds.get("height", 0) or 0)
        if asset_width <= 0 or asset_height <= 0:
            return False
        asset_right = asset_left + asset_width
        asset_bottom = asset_top + asset_height
        overflow_left = max(0.0, section_left - asset_left)
        overflow_top = max(0.0, section_top - asset_top)
        overflow_right = max(0.0, asset_right - section_right)
        overflow_bottom = max(0.0, asset_bottom - section_bottom)
        if (
            max(overflow_left, overflow_right) < overflow_x_threshold
            and max(overflow_top, overflow_bottom) < overflow_y_threshold
        ):
            return False
        if asset_width * asset_height < section_area * 0.12:
            return False
        return True

    def _asset_rules(self, asset: dict[str, Any], *, order: int, stack_override: str = "") -> list[str]:
        if asset.get("render") is False:
            return []
        class_name = ensure_text(asset.get("class_name"))
        if not class_name:
            return []
        bounds = asset.get("bounds", {})
        z_index = self._asset_z_index(asset, order, stack_override=stack_override)
        lines = [
            "",
            f".{class_name} {{",
            *self._absolute_box_rules(bounds),
            f"  z-index: {z_index};",
        ]
        style_css = ensure_text(asset.get("style_css"))
        if style_css:
            for declaration in self._split_css(style_css):
                lines.append(f"  {declaration}")
        lines.append("}")
        return lines

    def _asset_z_index(self, asset: dict[str, Any], order: int, *, stack_override: str = "") -> int:
        purpose = ensure_text(asset.get("purpose")).lower()
        if stack_override == "background-bleed" and purpose == "decorative":
            return min(45, 5 + order)
        if stack_override == "foreground-overlay" and purpose == "decorative":
            return 350 + order
        if purpose == "decorative" and self._is_shadow_shape(asset):
            return 40 + order
        if purpose == "background":
            return 50 + order
        if purpose == "foreground":
            return 350 + order
        if purpose in {"decorative", "mask"}:
            return 100 + order
        if purpose == "icon":
            return 300 + order
        return 250 + order

    def _infer_asset_stack_overrides(self, section: dict[str, Any]) -> dict[str, str]:
        overrides: dict[str, str] = {}
        prior_content_assets: list[dict[str, Any]] = []
        metadata = section.get("metadata", {}) or {}
        source_node_type = ensure_text(metadata.get("sourceNodeType")).upper()
        for asset in self._iter_assets(section.get("children", [])):
            purpose = ensure_text(asset.get("purpose")).lower()
            if purpose == "content":
                prior_content_assets.append(asset)
                continue
            if purpose != "decorative":
                continue
            if source_node_type == "GROUP" and self._has_large_decorative_overflow(asset, section):
                asset_id = ensure_text(asset.get("id") or asset.get("node_id"))
                if asset_id:
                    overrides[asset_id] = "background-bleed"
                continue
            if any(self._bounds_overlap_as_overlay(asset.get("bounds", {}), other.get("bounds", {})) for other in prior_content_assets):
                asset_id = ensure_text(asset.get("id") or asset.get("node_id"))
                if asset_id:
                    overrides[asset_id] = "foreground-overlay"
        return overrides

    def _iter_assets(self, nodes: list[dict[str, Any]]):
        for node in nodes:
            if node.get("kind") == "asset":
                asset = node.get("asset", {})
                if asset:
                    yield asset
            yield from self._iter_assets(node.get("children", []))

    def _is_shadow_shape(self, asset: dict[str, Any]) -> bool:
        render_mode = ensure_text(asset.get("render_mode") or asset.get("renderMode")).lower()
        style = asset.get("style", {}) or {}
        return render_mode == "shape" and bool(style.get("boxShadow"))

    def _bounds_overlap_as_overlay(self, first: dict[str, Any], second: dict[str, Any]) -> bool:
        first_left = float(first.get("x", 0) or 0)
        first_top = float(first.get("y", 0) or 0)
        first_width = float(first.get("width", 0) or 0)
        first_height = float(first.get("height", 0) or 0)
        second_left = float(second.get("x", 0) or 0)
        second_top = float(second.get("y", 0) or 0)
        second_width = float(second.get("width", 0) or 0)
        second_height = float(second.get("height", 0) or 0)
        if min(first_width, first_height, second_width, second_height) <= 0:
            return False
        overlap_width = min(first_left + first_width, second_left + second_width) - max(first_left, second_left)
        overlap_height = min(first_top + first_height, second_top + second_height) - max(first_top, second_top)
        if overlap_width <= 0 or overlap_height <= 0:
            return False
        overlap_area = overlap_width * overlap_height
        first_area = first_width * first_height
        second_area = second_width * second_height
        if first_area > second_area * 1.8:
            return False
        smaller_area = min(first_width * first_height, second_width * second_height)
        return overlap_area / max(smaller_area, 1.0) >= 0.08

    def _absolute_box_rules(self, bounds: dict[str, Any], *, include_height: bool = True) -> list[str]:
        left = float(bounds.get("x", 0) or 0)
        top = float(bounds.get("y", 0) or 0)
        width = float(bounds.get("width", 0) or 0)
        height = float(bounds.get("height", 0) or 0)
        lines = [
            f"  left: {left:.2f}px;",
            f"  top: {top:.2f}px;",
        ]
        if width > 0:
            lines.append(f"  width: {width:.2f}px;")
        if include_height and height > 0:
            lines.append(f"  height: {height:.2f}px;")
        return lines

    def _split_css(self, style_css: str) -> list[str]:
        declarations = []
        for item in style_css.split(";"):
            stripped = item.strip()
            if not stripped:
                continue
            declarations.append(f"{stripped};")
        return declarations
